name: learn-github-actions
on:
   push:
      branches: [main]
   pull_request:
      branches: [main]
jobs:
   pipeline:
      runs-on: ubuntu-latest
      strategy:
         matrix:
            node-version: [17.x]
      steps:
         - run: echo "Some text"
